app:
  env: dev
  redis:
    server: redis_host:6379
    database: 0
    password: your_password
    timeout: 2000

logging:
  config: classpath:log4j2-prod.xml

om.adc.domain: replace_with_your_om.adc.domain

admob:
  client_id: replace_with_your_googleapi.client_id
  client_secret: replace_with_your_googleapi.client_secret

spring:
  ## datasource
  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://mysql_host/open_mediation?useCursorFetch=true&characterEncoding=utf8&useSSL=true&requireSSL=false
      username: user
      password: pwd



