app:
  env: dev
  redis:
    server: 192.168.254.203:6379
    timeout: 2000

logging:
  config: classpath:log4j2-dev.xml

om.adc.domain: http://localhost:19014

spring:
  ## datasource
  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.254.204:3306/open_mediation?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
      username: diankou
      password: Diankou@!123


